# Generated by Django 5.2.1 on 2025-09-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_installmentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mpesa_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('mpesa', 'MPesa'), ('credit', 'Credit'), ('installment', 'Installment')], max_length=20),
        ),
    ]
