# Generated by Django 5.2.1 on 2025-10-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_customer_payment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'MPesa')], max_length=20),
        ),
    ]
