# Generated by Django 5.2.1 on 2025-11-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_payment_na_reason_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='split_data',
            field=models.JSONField(blank=True, help_text='Split payment data for split payments', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'MPesa'), ('split', 'Split')], max_length=20),
        ),
    ]
