# Generated by Django 5.2.1 on 2025-09-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('cashier', 'Cashier'), ('storekeeper', 'Storekeeper'), ('repair_technician', 'Repair Technician'), ('manager', 'Manager')], default='cashier', max_length=20),
        ),
    ]
