# Generated by Django 5.2.1 on 2025-10-05 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20251004_1815'),
        ('suppliers', '0002_auto_20251004_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='expected_delivery',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.purchaseorder'),
        ),
    ]
