# Generated by Django 5.2.1 on 2025-11-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_supplier_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='branch',
        ),
    ]
