# Generated by Django 5.2.1 on 2025-09-22 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mobile_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('discrepancy', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shifts', to='users.userprofile')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
