# Generated by Django 5.2.1 on 2025-11-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shift_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='branch',
        ),
    ]
