# Generated by Django 5.2.1 on 2025-10-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier_saleshistory_purchase_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wholesale_min_qty',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
