# Generated by Django 5.2.1 on 2025-10-04 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_wholesale_min_qty_product_wholesale_price'),
        ('suppliers', '0002_auto_20251004_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='suppliers.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='batch',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('received', 'Received'), ('expired', 'Expired')], default='ordered', max_length=20),
        ),
    ]
