# Generated by Django 5.2.1 on 2025-10-05 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20251004_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price per unit for this batch', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.batch'),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='saleshistory',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
