# Generated by Django 5.2.1 on 2025-10-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_add_wholesale_fields'),
        ('inventory', '0009_add_batch_fields'),
    ]

    operations = [
    ]
