# Generated by Django 5.2.1 on 2025-10-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_merge_0008_add_wholesale_fields_0009_add_batch_fields'),
        ('inventory', '0011_add_stockmovement_product_field'),
    ]

    operations = [
    ]
