# Generated by Django 5.2.1 on 2025-11-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_batch_branch_category_branch_pricehistory_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='category',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='saleshistory',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='branch',
        ),
    ]
