# Generated by Django 5.2.1 on 2025-10-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_add_batch_supplier_field'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryanalytics',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='received_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryanalytics',
            name='sold_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesreport',
            name='average_transaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryanalytics',
            unique_together={('product', 'date')},
        ),
    ]
