# Generated by Django 5.2.1 on 2025-10-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_business_name_customer_credit_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='credit_balance',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='credit_limit',
        ),
    ]
