# Generated by Django 5.2.1 on 2025-10-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('retail', 'Retail Sale'), ('wholesale', 'Wholesale Sale')], default='retail', max_length=10),
        ),
    ]
