# Generated by Django 5.2.1 on 2025-10-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('held', 'Held')], default='open', max_length=10),
        ),
    ]
