# Generated by Django 5.2.1 on 2025-10-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('held', 'Held'), ('voided', 'Voided')], default='open', max_length=10),
        ),
    ]
