# Generated by Django 5.2.1 on 2025-11-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_voided_sale_void_reason_sale_voided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='incomplete_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
