# Generated by Django 5.2.1 on 2025-11-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_sale_incomplete_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='incomplete_reason',
        ),
    ]
