# Generated by Django 5.2.1 on 2025-11-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_cart_branch_invoice_branch_return_branch_sale_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='return',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='branch',
        ),
    ]
